config/routes.rb
Rails.application.routes.draw do
  devise_for :logins
  
  resources :bookings
  #get 'home/index'
 
  root 'home#index'
  get 'home/about'
 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
end

app/models/login.rb
class Login < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy!

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:client_name, :email, :phone, :appointment_date, :additional_information, :payment_type, :consultant_preference)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p>
    <strong>Client name:</strong>
    <%= booking.client_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= booking.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= booking.phone %>
  </p>

  <p>
    <strong>Appointment date:</strong>
    <%= booking.appointment_date %>
  </p>

  <p>
    <strong>Additional information:</strong>
    <%= booking.additional_information %>
  </p>

  <p>
    <strong>Payment type:</strong>
    <%= booking.payment_type %>
  </p>

  <p>
    <strong>Consultant preference:</strong>
    <%= booking.consultant_preference %>
  </p>

</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <% if booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :client_name, style: "display: block" %>
    <%= form.text_field :client_name , placeholder: "Enter Client Name" %> 
  </div>
 <br>
  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, placeholder: "Enter Email" %>
  </div>
 <br>
  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, placeholder: "Enter Phone Number" %>
  </div>
  <br>
  <div>
    <%= form.label :appointment_date, style: "display: block" %>
    <%= form.datetime_field :appointment_date %>
  </div>
  <br>
  <div>
    <%= form.label :additional_information, style: "display: block" %>
    <%= form.text_field :additional_information, placeholder: "Enter Any Additional Information" %>
    <br>
  </div>

  <div>
    <%= form.label :payment_type, style: "display: block" %>
    <%= form.select:payment_type,  options_for_select([['Online', 'Online'], ['In-Person', 'In-Person']])%>
   
  </div>
  <br>
  <div>
    <%= form.label :consultant_preference, style: "display: block" %>
       <%= form.select:consultant_preference, options_for_select([['Select Consultant', 'Other Consultants'], 
       ['Sarah Corner', 'In-Sarah Corner'], ['Mathew Jenkins', 'Mathew Jenkins'], ['Ayobamidele Martins', 'Ayobamidele Martins'], ['Donna Specter', 'Donna Specter']])%>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Show this booking", @booking %> |
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Booking List</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Client Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Appointment Date</th>
      <th scope="col">Additional Information</th>
      <th scope="col">Payment Type</th>
      <th scope="col">Consultant Preference</th>
    </tr>
  </thead>
 <tbody>
 <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.client_name %></td>
        <td><%= booking.email %></td>
        <td><%= booking.phone %></td>
        <td><%= booking.appointment_date %></td>
        <td><%= booking.additional_information %></td>
        <td><%= booking.payment_type %></td>
        <td><%= booking.consultant_preference %></td>
        <td>
          <%= link_to "Show", booking, class: "btn btn-outline-primary btn-sm" %>
          <%= link_to 'Delete', booking, method: :delete, class: "btn btn-outline-danger btn-sm"%>
          <%= link_to 'Edit', edit_booking_path(booking), class: "btn btn-outline-primary btn-sm" %>
          <% @bookings.each do |booking| %>
          </td>  
 
  </tbody>

<% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New booking", new_booking_path %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container mt-5">
  <div class="mt-4 p-5 bg-secondary text-white rounded">
    <h1>Bookings</h1> 
    <p> <%= render @booking %> </p> 
  </div>
</div>
<br>
<div>
 
  <%= link_to "Edit this booking", edit_booking_path(@booking), class: "btn btn-outline-primary btn-sm" %> 

  <%= link_to "Back to bookings", bookings_path, class: "btn btn-outline-primary btn-sm" %>

  <%= button_to "Delete this Booking", @booking, method: :delete, class: "btn btn-outline-primary btn-sm" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: #a71aeb;">
<%= link_to 'BCS', root_path, class: "navbar-brand"%>
  <div class="container-fluid">
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
       

           <li class="nav-item">
        <%= link_to'Bookings', bookings_path, class: "nav-link"%>
          
        </li>
            <li class="nav-item">
        <%= link_to'  Sign Up', new_login_registration_path, class: "nav-link"%>
          
        </li>

         </li>
            <li class="nav-item">
        <%= link_to'  Sign In', login_session_path, class: "nav-link"%>
          
        </li>
       
            <li class="nav-item">
        <%= link_to'Edit Profile', edit_login_registration_path, class: "nav-link"%>
          
        </li>
        

           <li class="nav-item">
        <%= link_to'Add Bookings', new_booking_path, class: "nav-link"%>
          
        </li>
         <li class="nav-item">
        <%= link_to'User Guide', home_about_path, class: "nav-link"%>
          
        </li>
        
       
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About </h1>

app/views/home/index.html.erb
<h1>Bookings</h1>
<p>Find me in app/viewshome/index.html.erb</p/>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <title>Bookings</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
       <%= render 'home/header' %> 
      <div class= "container">
    <br/>
      <%= yield %>
     </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>





<!DOCTYPE html>
<html>
  <head>
    <title>Bookings</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   
  </body>
</html>